import {
  Paciente,
  Profissional,
  PlanoSaude,
  Procedimento,
  Agendamento,
  GuiaSadt,
  LoteTiss,
  SenhaPlano,
  ListaEspera,
  Historico,
  FechamentoMensal,
  PagamentoTerapeuta,
  ControleMeses,
  Usuario,
  PerfilAcesso,
  StatusAgendamento
} from '../types';

export const mappers = {
  pacToDb: (p: Partial<Paciente>) => ({
    nome: p.nome,
    nasc: p.nasc || null,
    cpf: p.cpf || null,
    tel: p.tel || null,
    email: p.email || null,
    end: p.end || null,
    logradouro: p.logradouro || null,
    numero: p.numero || null,
    complemento: p.complemento || null,
    bairro: p.bairro || null,
    cep: p.cep || null,
    cidade: p.cidade || null,
    uf_end: p.ufEnd || null,
    plano_id: p.planoId || 5,
    plano: p.plano || 'Particular',
    carteirinha: p.carteirinha || null,
    sexo: p.sexo || null,
    status: p.status || 'Ativo',
    obs: p.obs || null,
    ultima: p.ultima || null,
    est_civil: p.estCivil || null,
    profissao: p.profissao || null,
    titular: p.titular || null,
    foto: p.foto || null,
    senha_chat: p.senhaChat || null
  }),
  dbToPac: (r: any): Paciente => ({
    id: r.id,
    nome: r.nome,
    nasc: r.nasc || '',
    cpf: r.cpf || '',
    tel: r.tel || '',
    email: r.email || '',
    end: r.end || '',
    logradouro: r.logradouro || '',
    numero: r.numero || '',
    complemento: r.complemento || '',
    bairro: r.bairro || '',
    cep: r.cep || '',
    cidade: r.cidade || '',
    ufEnd: r.uf_end || r.ufEnd || '',
    planoId: r.plano_id || 5,
    plano: r.plano || 'Particular',
    carteirinha: r.carteirinha || '—',
    sexo: r.sexo || '',
    status: r.status || 'Ativo',
    obs: r.obs || '',
    ultima: r.ultima || '',
    estCivil: r.est_civil || '',
    profissao: r.profissao || '',
    titular: r.titular || '',
    foto: r.foto || '',
    senhaChat: r.senha_chat || r.senhaChat || ''
  }),

  profToDb: (p: Partial<Profissional>) => ({
    nome: p.nome,
    nome_agenda: p.nomeAgenda || null,
    esp: p.esp || null,
    conselho: p.conselho || null,
    num: p.num || null,
    uf: p.uf || 'SP',
    cbo: p.cbo || null,
    tel: p.tel || null,
    email: p.email || null,
    cor: p.cor || '#4f8ef7',
    status: p.status || 'Ativo',
    foto: p.foto || null,
    instagram: p.instagram || null,
    linkedin: p.linkedin || null,
    google_cal_id: p.googleCalendarId || null,
    valor_30: p.valor30 || 0,
    valor_60: p.valor60 || 0,
    valor_aval: p.valorAval || 0,
    valor_particular: p.valorParticular || 0,
    valor_desmarque_apos18: p.valorDesmarqueApos18 || 0,
    conta_tipo: p.contaTipo || 'PF',
    pagar_como: p.pagarComo || 'pix',
    razao_social: p.razaoSocial || null,
    pix: p.pix || null,
    banco: p.banco || null,
    agencia: p.agencia || null,
    conta: p.conta || null
  }),
  dbToProf: (r: any): Profissional => ({
    id: r.id,
    nome: r.nome,
    nomeAgenda: r.nome_agenda || r.nome?.split(' ')[0] || '',
    esp: r.esp || '',
    conselho: r.conselho || '',
    num: r.num || '',
    uf: r.uf || 'SP',
    cbo: r.cbo || '',
    tel: r.tel || '',
    email: r.email || '',
    cor: r.cor || '#4f8ef7',
    status: r.status || 'Ativo',
    foto: r.foto || '',
    instagram: r.instagram || '',
    linkedin: r.linkedin || '',
    googleCalendarId: r.google_cal_id || '',
    valor30: r.valor_30 || 0,
    valor60: r.valor_60 || 0,
    valorAval: r.valor_aval || 0,
    valorParticular: r.valor_particular || 0,
    valorDesmarqueApos18: r.valor_desmarque_apos18 || 0,
    contaTipo: r.conta_tipo || 'PF',
    pagarComo: r.pagar_como || 'pix',
    razaoSocial: r.razao_social || '',
    pix: r.pix || '',
    banco: r.banco || '',
    agencia: r.agencia || '',
    conta: r.conta || ''
  }),

  planoToDb: (p: Partial<PlanoSaude>) => ({
    nome: p.nome,
    nome_guia: p.nomeGuia || null,
    cnpj: p.cnpj || null,
    ans: p.ans || null,
    tabela: p.tabela || 'CBHPM',
    cod_prestador: p.codPrestador || null,
    nome_contratado: p.nomeContratado || null,
    cnes: p.cnes || null,
    num_guia_inicial: p.numGuiaInicial || 1,
    usa_tiss: p.usaTiss !== false,
    aplica_todos: p.aplicaTodos !== false,
    tipo_id: p.tipoId || 'Código',
    versao_tiss: p.versaoTiss || '4.02.00',
    tel: p.tel || null,
    email: p.email || null,
    obs: p.obs || null,
    status: p.status || 'Ativo',
    juntar_guia: p.juntarGuia !== false,
    nome_plano_guia: p.nomePlanoGuia || null,
    logo: p.logo || p.foto || null,
    foto: p.logo || p.foto || null,
    foto_url: p.logo || p.foto || null
  }),
  dbToPlano: (r: any): PlanoSaude => ({
    id: r.id,
    nome: r.nome,
    nomeGuia: r.nome_guia || '',
    cnpj: r.cnpj || '',
    ans: r.ans || '',
    tabela: r.tabela || 'CBHPM',
    codPrestador: r.cod_prestador || '',
    nomeContratado: r.nome_contratado || '',
    cnes: r.cnes || '',
    numGuiaInicial: r.num_guia_inicial || 1,
    usaTiss: r.usa_tiss !== false,
    aplicaTodos: r.aplica_todos !== false,
    tipoId: r.tipo_id || 'Código',
    versaoTiss: r.versao_tiss || '4.02.00',
    tel: r.tel || '',
    email: r.email || '',
    obs: r.obs || '',
    status: r.status || 'Ativo',
    pacientes: r.pacientes || 0,
    juntarGuia: r.juntar_guia !== false,
    nomePlanoGuia: r.nome_plano_guia || '',
    logo: r.logo || r.foto || r.foto_url || '',
    foto: r.foto || r.logo || r.foto_url || ''
  }),

  procToDb: (p: Partial<Procedimento>) => ({
    codigo: p.codigo || null,
    descricao: p.desc,          // banco usa coluna 'descricao'
    desc_curta: p.descCurta || null,
    tipo: p.tipo || 'Sessão',
    val_part: p.valPart || 0,
    val_plano: p.valPlano || 0,
    tabela: p.tabela || 'TUSS',
    plano_id: p.planoId || 0,
    codigo_servico_abrasf: p.codigoServicoAbrasf || '04.01',
    status: p.status || 'Ativo',
    obs: p.obs || null
  }),
  dbToProc: (r: any): Procedimento => ({
    id: r.id,
    codigo: r.codigo || '',
    desc: r.descricao || r.desc || '',   // banco usa coluna 'descricao'
    descCurta: r.desc_curta || '',
    tipo: r.tipo || 'Sessão',
    valPart: Number(r.val_part) || 0,
    valPlano: Number(r.val_plano) || 0,
    tabela: r.tabela || 'TUSS',
    planoId: r.plano_id || 0,
    codigoServicoAbrasf: r.codigo_servico_abrasf || r.codigoServicoAbrasf || '04.01',
    status: r.status || 'Ativo',
    obs: r.obs || ''
  }),

  apptToDb: (a: Partial<Agendamento>) => ({
    prof_id: a.profId,
    pac_id: a.pacId || null,
    paciente: a.paciente,
    plano: a.plano || 'Particular',
    plano_id: a.planoId || 5,
    hora: a.hora,
    hora_fim: a.horaFim || null,
    dur_min: a.durMin || 30,
    data_iso: a.dataISO || null,
    status: a.status || 'agendado',
    obs: a.obs || null,
    modalidade: a.modalidade || 'presencial',
    meet_link: a.meetLink || null,
    wa_sent: a.waSent || false,
    carteirinha: a.carteirinha || null,
    guia: a.guia || null,
    tipo: a.tipo || 'sessao'
  }),
  dbToAppt: (r: any): Agendamento => ({
    id: r.id,
    profId: r.prof_id,
    pacId: r.pac_id || null,
    paciente: r.paciente,
    plano: r.plano || 'Particular',
    planoId: r.plano_id,
    hora: r.hora,
    horaFim: r.hora_fim || '',
    durMin: r.dur_min || 30,
    dataISO: r.data_iso || '',
    status: r.status || 'agendado',
    obs: r.obs || '',
    modalidade: r.modalidade || 'presencial',
    meetLink: r.meet_link || '',
    waSent: r.wa_sent || false,
    carteirinha: r.carteirinha || '',
    guia: r.guia || null,
    tipo: r.tipo || 'sessao'
  }),

  guiaToDb: (g: Partial<GuiaSadt>) => ({
    num: g.num,
    pac: g.pac,
    pac_id: g.pacId || null,
    agendamento_id: g.agendamentoId || null,
    codigo_procedimento: g.codigoProcedimento || null,
    plano_id: g.planoId,
    plano: g.plano,
    prof_id: g.profId,
    valor: g.valor || 0,
    status: g.status || 'Pendente',
    data: g.data || null,
    lote_id: g.loteId || null,
    lote_num: g.loteNum || null,
    dados: g.dados || null,
    carteirinha: g.carteirinha || null,
    num_op: g.numOp || null,
    cid: g.cid || null
  }),
  dbToGuia: (r: any): GuiaSadt => ({
    id: r.id,
    num: r.num,
    pac: r.pac,
    pacId: r.pac_id || null,
    agendamentoId: r.agendamento_id || null,
    codigoProcedimento: r.codigo_procedimento || null,
    planoId: r.plano_id,
    plano: r.plano,
    profId: r.prof_id,
    valor: Number(r.valor) || 0,
    status: r.status || 'Pendente',
    data: r.data || '',
    loteId: r.lote_id || null,
    loteNum: r.lote_num || null,
    dados: r.dados || {},
    carteirinha: r.carteirinha || '',
    numOp: r.num_op || '',
    cid: r.cid || ''
  }),

  loteToDb: (l: Partial<LoteTiss>) => ({
    num: l.num,
    competencia: l.competencia,
    plano_id: l.planoId,
    plano: l.plano,
    qtd: l.qtd || 0,
    valor: l.valor || 0,
    status: l.status || 'Pendente',
    data_criacao: l.dataCriacao || null,
    data_envio: l.dataEnvio || null,
    obs: l.obs || null,
    guia_ids: l.guiaIds || []
  }),
  dbToLote: (r: any): LoteTiss => ({
    id: r.id,
    num: r.num,
    competencia: r.competencia,
    planoId: r.plano_id,
    plano: r.plano,
    qtd: r.qtd || 0,
    valor: Number(r.valor) || 0,
    status: r.status || 'Pendente',
    dataCriacao: r.data_criacao || '',
    dataEnvio: r.data_envio || '',
    obs: r.obs || '',
    guiaIds: r.guia_ids || [],
    xml: ''
  }),

  senhaToDb: (s: Partial<SenhaPlano>) => ({
    plano_id: s.planoId,
    paciente: s.paciente,
    carteirinha: s.carteirinha || null,
    num_guia_op: s.numGuiaOp || null,
    num_senha: s.numSenha,
    data_aut: s.dataAut || null,
    validade: s.validade || null,
    qtd_autorizada: s.qtdAutorizada || 10,
    qtd_usada: s.qtdUsada || 0,
    cid: s.cid || null,
    obs: s.obs || null,
    status: s.status || 'Ativa',
    procs: s.procs || null,
    ativa: s.ativa !== false,
    procedimento: s.procedimento || null,
    agendamento_id: s.agendamentoId || null,
    prof_solicitante: s.profSolicitante || null,
    prof_solicitante_conselho: s.profSolicitanteConselho || null,
    prof_solicitante_num_conselho: s.profSolicitanteNumConselho || null,
    prof_solicitante_uf: s.profSolicitanteUf || null,
    prof_solicitante_cbo: s.profSolicitanteCbo || null
  }),
  dbToSenha: (r: any): SenhaPlano => ({
    id: r.id,
    planoId: r.plano_id,
    paciente: r.paciente,
    carteirinha: r.carteirinha || '',
    numGuiaOp: r.num_guia_op || '',
    numSenha: r.num_senha,
    dataAut: r.data_aut || '',
    validade: r.validade || '',
    qtdAutorizada: r.qtd_autorizada || 10,
    qtdUsada: r.qtd_usada || 0,
    cid: r.cid || '',
    obs: r.obs || '',
    status: r.status || 'Ativa',
    procs: r.procs || [],
    ativa: r.ativa !== false,
    procedimento: r.procedimento || null,
    agendamentoId: r.agendamento_id || null,
    profSolicitante: r.prof_solicitante || r.profSolicitante || '',
    profSolicitanteConselho: r.prof_solicitante_conselho || r.profSolicitanteConselho || '',
    profSolicitanteNumConselho: r.prof_solicitante_num_conselho || r.profSolicitanteNumConselho || '',
    profSolicitanteUf: r.prof_solicitante_uf || r.profSolicitanteUf || '',
    profSolicitanteCbo: r.prof_solicitante_cbo || r.profSolicitanteCbo || ''
  }),

  esperaToDb: (e: Partial<ListaEspera>) => ({
    nome: e.nome,
    tel: e.tel,
    email: e.email || null,
    nasc: e.nasc || null,
    end: e.end || null,
    plano: e.plano || null,
    carteirinha: e.carteirinha || null,
    especialidade: e.especialidade || null,
    idade: e.idade || null,
    periodo: e.periodo || null,
    obs: e.obs || null,
    dias: e.dias || [],
    periodos: e.periodos || [],
    procedimentos: e.procedimentos || [],
    status: e.status || 'Aguardando',
    data_entrada: e.dataEntrada || e.dataCadastro || null,
    data_cadastro: e.dataCadastro || e.dataEntrada || null
  }),
  dbToEspera: (r: any): ListaEspera => ({
    id: r.id,
    nome: r.nome,
    tel: r.tel || '',
    email: r.email || '',
    nasc: r.nasc || '',
    end: r.end || '',
    plano: r.plano || '',
    carteirinha: r.carteirinha || '',
    especialidade: r.especialidade || '',
    idade: r.idade || '',
    periodo: r.periodo || '',
    obs: r.obs || '',
    dias: r.dias || [],
    periodos: r.periodos || [],
    procedimentos: r.procedimentos || [],
    status: r.status || 'Aguardando',
    dataEntrada: r.data_entrada || r.data_cadastro || '',
    dataCadastro: r.data_cadastro || r.data_entrada || ''
  }),

  histToDb: (h: Partial<Historico>) => ({
    pac_id: h.pacId,
    tipo: h.tipo,
    titulo: h.titulo || null,
    conteudo: h.conteudo || null,
    prof_id: h.profId || null,
    data: h.data || null,
    status: h.status || null,
    fonte: h.fonte || null
  }),
  dbToHist: (r: any): Historico => {
    let parsedConteudo = r.conteudo;
    if (typeof parsedConteudo === 'string') {
      try {
        parsedConteudo = JSON.parse(parsedConteudo);
      } catch (e) {
        parsedConteudo = { texto: r.conteudo };
      }
    }
    return {
      id: r.id,
      pacId: r.pac_id,
      tipo: r.tipo,
      titulo: r.titulo || '',
      conteudo: parsedConteudo || {},
      profId: r.prof_id || null,
      data: r.data || '',
      status: r.status || '',
      fonte: r.fonte || ''
    };
  },

  fechamentoToDb: (f: Partial<FechamentoMensal>) => ({
    competencia: f.competencia,
    total_sessoes: f.totalSessoes || 0,
    total_valor: f.totalValor || 0,
    total_profissionais: f.totalProfissionais || 0,
    detalhes: f.detalhes || null,
    confirmado_por: f.confirmadoPor || null,
    confirmado_em: f.confirmadoEm || null
  }),
  dbToFechamento: (r: any): FechamentoMensal => ({
    id: r.id,
    competencia: r.competencia,
    totalSessoes: r.total_sessoes || 0,
    totalValor: Number(r.total_valor) || 0,
    totalProfissionais: r.total_profissionais || 0,
    detalhes: r.detalhes || {},
    confirmadoPor: r.confirmado_por || '',
    confirmadoEm: r.confirmado_em || ''
  }),

  pagamentoToDb: (p: Partial<PagamentoTerapeuta>) => ({
    id: p.id,
    profissional_id: p.profissionalId || null,
    profissional_nome: p.profissional || null,
    competencia: p.competencia || null,
    tipo_terapia: p.tipo || null,
    qtd_pacientes: p.qtdPacientes || 0,
    valor_a_receber: p.valor || 0,
    status_pagamento: p.status || 'pendente',
    valor_pago: p.valorPago || 0,
    data_pagamento: p.dataPagamento || null,
    nota_fiscal_url: p.nfUrl || null,
    nota_fiscal_nome: p.nfNome || null,
    obs: p.obs || null
  }),
  dbToPagamento: (r: any): PagamentoTerapeuta => ({
    id: r.id,
    profissionalId: r.profissional_id || null,
    profissional: r.profissional_nome || '',
    competencia: r.competencia || '',
    tipo: r.tipo_terapia || 'sessao',
    qtdPacientes: r.qtd_pacientes || 0,
    valor: Number(r.valor_a_receber) || 0,
    status: r.status_pagamento || 'pendente',
    valorPago: Number(r.valor_pago) || 0,
    dataPagamento: r.data_pagamento || '',
    nfUrl: r.nota_fiscal_url || '',
    nfNome: r.nota_fiscal_nome || '',
    obs: r.obs || '',
    criadoEm: r.criado_em || '',
    atualizadoEm: r.atualizado_em || ''
  }),
  controleToDb: (c: Partial<ControleMeses>) => ({
    ano_mes: c.anoMes,
    status: c.status || 'aberto',
    obs: c.obs || null,
    alterado_por: c.alteradoPor || null
  }),
  dbToControle: (r: any): ControleMeses => ({
    id: r.id,
    anoMes: r.ano_mes || '',
    status: r.status || 'aberto',
    obs: r.obs || '',
    alteradoPor: r.alterado_por || '',
    createdAt: r.created_at || '',
    updatedAt: r.updated_at || ''
  }),
  usuarioToDb: (u: Partial<Usuario>) => {
    const res: any = {
      id: u.id,
      nome: u.nome,
      email: u.email,
      cpf: u.cpf || null,
      rg: u.rg || null,
      telefone: u.tel || null,
      data_nascimento: u.nasc || null,
      perfil: u.perfil,
      status: u.status,
      foto: u.foto || null,
      prof_id: u.profId || null,
      perfil_id: u.perfilId || null,
      created_at: u.criadoEm || new Date().toISOString()
    };
    if (u.senha) res.senha = u.senha;
    return res;
  },
  dbToUsuario: (r: any): Usuario => {
    const s = r.status;
    let statusVal: 'Ativo' | 'Inativo' = 'Ativo';

    if (
      s === 'Inativo' ||
      s === 'inativo' ||
      s === 'INATIVO' ||
      s === false ||
      s === 'false' ||
      s === 0 ||
      s === '0' ||
      s === 'Inativa' ||
      s === 'inativa'
    ) {
      statusVal = 'Inativo';
    }

    return {
      id: r.id,
      nome: r.nome || '',
      email: r.email || '',
      cpf: r.cpf || '',
      rg: r.rg || '',
      tel: r.telefone || r.tel || '',
      nasc: r.data_nascimento || r.nasc || '',
      perfil: r.perfil || 'admin',
      perfilId: r.perfil_id || null,
      status: statusVal,
      foto: r.foto || r.foto_url || r.avatar || '',
      senha: r.senha || '',
      profId: r.prof_id || null,
      criadoEm: r.created_at || ''
    };
  },
  perfilToDb: (p: Partial<PerfilAcesso>) => ({
    id: p.id,
    nome: p.nome,
    desc: p.desc || null,
    cor: p.cor || '#6366f1',
    modulos: JSON.stringify(p.modulos || []),
    sub_perms: JSON.stringify(p.subPerms || {})
  }),
  dbToPerfil: (r: any): PerfilAcesso => ({
    id: r.id,
    nome: r.nome || '',
    desc: r.desc || '',
    cor: r.cor || '#6366f1',
    bloqueado: false,
    modulos: typeof r.modulos === 'string' ? JSON.parse(r.modulos) : (r.modulos || []),
    subPerms: typeof r.sub_perms === 'string' ? JSON.parse(r.sub_perms) : (r.sub_perms || {})
  }),
  statusAgToDb: (s: Partial<StatusAgendamento>) => ({
    nome: s.nome,
    cor: s.cor || '#4f8ef7',
    status_agendamento: s.statusAgendamento || 'agendado',
    status_historico: s.statusHistorico || null
  }),
  dbToStatusAg: (r: any): StatusAgendamento => ({
    id: r.id,
    nome: r.nome || '',
    cor: r.cor || '#4f8ef7',
    statusAgendamento: r.status_agendamento || 'agendado',
    statusHistorico: r.status_historico || '',
    createdAt: r.created_at || ''
  }),

  // Conecta Mappings
  salaToDb: (s: any) => ({
    nome: s.nome,
    descricao: s.descricao || null,
    capacidade: s.capacidade || 2,
    cor: s.cor || 'sala1',
    ativo: s.ativo !== false
  }),
  dbToSala: (r: any) => ({
    id: r.id,
    nome: r.nome,
    descricao: r.descricao || '',
    capacidade: r.capacidade || 2,
    cor: r.cor || 'sala1',
    ativo: r.ativo !== false
  }),
  locToDb: (l: any) => ({
    nome: l.nome,
    especialidade: l.esp || null,
    telefone: l.tel || null,
    email: l.email || null,
    cpf: l.cpf || null,
    conselho: l.conselho || null,
    valor_hora: l.valorHora || 0,
    valor_meio: l.valorMeio || 0,
    valor_dia: l.valorDia || 0,
    sala_pref_id: l.salaPref || null,
    status: l.status || 'ativo',
    obs: l.obs || null
  }),
  dbToLoc: (r: any) => ({
    id: r.id,
    nome: r.nome,
    esp: r.especialidade || '',
    tel: r.telefone || '',
    email: r.email || '',
    cpf: r.cpf || '',
    conselho: r.conselho || '',
    valorHora: r.valor_hora || 0,
    valorMeio: r.valor_meio || 0,
    valorDia: r.valor_dia || 0,
    salaPref: r.sala_pref_id || '',
    status: r.status || 'ativo',
    obs: r.obs || ''
  }),
  resToDb: (r: any) => ({
    sala_id: r.salaId,
    locatario_id: r.locId,
    data: r.data,
    hora_ini: r.horaIni,
    hora_fim: r.horaFim,
    dur_min: r.durMin || 60,
    recorrencia: r.recorrencia || 'unica',
    serie_id: r.serieId || null,
    status: r.status || 'confirmado',
    obs: r.obs || null,
    valor_cobrado: r.valorCobrado || null
  }),
  dbToRes: (r: any) => ({
    id: r.id,
    salaId: r.sala_id,
    locId: r.locatario_id,
    data: r.data,
    horaIni: r.hora_ini?.slice(0, 5) || '',
    horaFim: r.hora_fim?.slice(0, 5) || '',
    durMin: r.dur_min || 60,
    recorrencia: r.recorrencia || 'unica',
    serieId: r.serie_id || null,
    status: r.status || 'confirmado',
    obs: r.obs || '',
    valorCobrado: r.valor_cobrado || null
  }),
  fechToDb: (f: any) => ({
    competencia: f.competencia,
    locatario_id: f.locatarioId,
    total_reservas: f.totalReservas || 0,
    total_horas: f.totalHoras || 0,
    total_valor: f.totalValor || 0,
    status: f.status || 'emitido',
    emitido_em: f.emitidoEm || new Date().toISOString(),
    detalhes: f.detalhes ? (typeof f.detalhes === 'string' ? f.detalhes : JSON.stringify(f.detalhes)) : null
  }),
  dbToFech: (r: any) => ({
    id: r.id,
    competencia: r.competencia,
    locatarioId: r.locatario_id,
    totalReservas: r.total_reservas || 0,
    totalHoras: r.total_horas || 0,
    totalValor: r.total_valor || 0,
    status: r.status || 'emitido',
    emitidoEm: r.emitido_em || '',
    detalhes: typeof r.detalhes === 'string' ? JSON.parse(r.detalhes || '[]') : (r.detalhes || [])
  }),
  nfToDb: (nf: Partial<import('../types').NotaFiscalJundiai>) => ({
    id: nf.id || `nf_${Date.now()}_${Math.floor(Math.random() * 1000)}`,
    numero_rps: nf.numeroRps,
    numero_lote: nf.numeroLote || null,
    numero_nota: nf.numeroNota || null,
    codigo_verificacao: nf.codigoVerificacao || null,
    data_emissao: nf.dataEmissao || new Date().toISOString(),
    paciente_id: nf.pacienteId || null,
    tomador_nome: nf.tomadorNome,
    tomador_cpf_cnpj: nf.tomadorCpfCnpj,
    tomador_email: nf.tomadorEmail || null,
    tomador_endereco: nf.tomadorEndereco || null,
    servico_codigo: nf.servicoCodigo,
    descricao_servico: nf.descricaoServico,
    valor_servico: nf.valorServico || 0,
    aliquota_iss: nf.aliquotaIss || 0,
    valor_iss: nf.valorIss || 0,
    cst_ibs_cbs: nf.cstIbsCbs || '01',
    c_class_trib: nf.cClassTribIbsCbs || '040100',
    aliquota_ibs: nf.aliquotaIbs || 0,
    valor_ibs: nf.valorIbs || 0,
    aliquota_cbs: nf.aliquotaCbs || 0,
    valor_cbs: nf.valorCbs || 0,
    p_redutor_ibs_cbs: nf.reducaoBaseIbsCbs || 60,
    status: nf.status || 'Rascunho',
    motivo_rejeicao: nf.motivoRejeicao || null,
    pdf_url: nf.pdfUrl || null,
    xml_url: nf.xmlUrl || null,
    xml_envio: nf.xmlEnvio || null,
    xml_resposta: nf.xmlResposta || null,
    ambiente: nf.ambiente || 'Homologação'
  }),
  dbToNf: (r: any): import('../types').NotaFiscalJundiai => ({
    id: String(r.id),
    numeroRps: r.numero_rps || '',
    numeroLote: r.numero_lote ? Number(r.numero_lote) : undefined,
    numeroNota: r.numero_nota || undefined,
    codigoVerificacao: r.codigo_verificacao || undefined,
    dataEmissao: r.data_emissao || r.created_at || '',
    pacienteId: r.paciente_id || null,
    tomadorNome: r.tomador_nome || '',
    tomadorCpfCnpj: r.tomador_cpf_cnpj || '',
    tomadorEmail: r.tomador_email || '',
    tomadorEndereco: r.tomador_endereco || '',
    servicoCodigo: r.servico_codigo || '04.01',
    descricaoServico: r.descricao_servico || '',
    valorServico: Number(r.valor_servico) || 0,
    aliquotaIss: Number(r.aliquota_iss) || 0,
    valorIss: Number(r.valor_iss) || 0,
    cstIbsCbs: r.cst_ibs_cbs || '01',
    cClassTribIbsCbs: r.c_class_trib || '040100',
    aliquotaIbs: Number(r.aliquota_ibs) || 0,
    valorIbs: Number(r.valor_ibs) || 0,
    aliquotaCbs: Number(r.aliquota_cbs) || 0,
    valorCbs: Number(r.valor_cbs) || 0,
    reducaoBaseIbsCbs: Number(r.p_redutor_ibs_cbs) || 60,
    status: r.status || 'Rascunho',
    motivoRejeicao: r.motivo_rejeicao || undefined,
    pdfUrl: r.pdf_url || undefined,
    xmlUrl: r.xml_url || undefined,
    xmlEnvio: r.xml_envio || undefined,
    xmlResposta: r.xml_resposta || undefined,
    ambiente: r.ambiente || 'Homologação',
    created_at: r.created_at || ''
  }),

  configFiscalToDb: (cfg: Partial<import('../types').ConfiguracaoFiscalJundiai>) => ({
    id: 'config_padrao',
    cnpj_emissor: cfg.cnpjEmissor,
    inscricao_municipal: cfg.inscricaoMunicipal,
    razao_social: cfg.razaoSocial,
    ambiente: cfg.ambiente || 'Homologação',
    codigo_servico_padrao: cfg.codigoServicoPadrao || '04.01',
    aliquota_iss_padrao: cfg.aliquotaIssPadrao || 2.0,
    optante_simples_nacional: cfg.optanteSimplesNacional !== false,
    serie_rps: cfg.serieRps || '1',
    proximo_numero_rps: cfg.proximoNumeroRps || 1001,
    proximo_numero_lote: cfg.proximoNumeroLote || 1001,
    regime_tributario: cfg.regimeTributario || '6',
    certificado_nome_arquivo: cfg.certificadoNomeArquivo || null,
    certificado_base64: cfg.certificadoBase64 || null,
    certificado_senha: cfg.certificadoSenha || null,
    destacar_ibs_cbs: cfg.destacarIbsCbs !== false,
    aliquota_ibs_padrao: cfg.aliquotaIbsPadrao || 0.10,
    aliquota_cbs_padrao: cfg.aliquotaCbsPadrao || 0.90,
    reducao_saude_ibs_cbs: cfg.reducaoSaudeIbsCbs || 60,
    certificado_validade: cfg.certificadoValidade || null,
    updated_at: new Date().toISOString()
  }),

  dbToConfigFiscal: (r: any): import('../types').ConfiguracaoFiscalJundiai => ({
    cnpjEmissor: r.cnpj_emissor || '',
    inscricaoMunicipal: r.inscricao_municipal || '',
    razaoSocial: r.razao_social || '',
    ambiente: r.ambiente || 'Homologação',
    codigoServicoPadrao: r.codigo_servico_padrao || '04.01',
    aliquotaIssPadrao: Number(r.aliquota_iss_padrao) || 2.0,
    optanteSimplesNacional: r.optante_simples_nacional !== false,
    serieRps: r.serie_rps || '1',
    proximoNumeroRps: Number(r.proximo_numero_rps) || 1001,
    proximoNumeroLote: Number(r.proximo_numero_lote) || 1001,
    regimeTributario: r.regime_tributario || '6',
    certificadoNomeArquivo: r.certificado_nome_arquivo || '',
    certificadoBase64: r.certificado_base64 || '',
    certificadoSenha: r.certificado_senha || '',
    destacarIbsCbs: r.destacar_ibs_cbs !== false,
    aliquotaIbsPadrao: Number(r.aliquota_ibs_padrao) || 0.10,
    aliquotaCbsPadrao: Number(r.aliquota_cbs_padrao) || 0.90,
    reducaoSaudeIbsCbs: Number(r.reducao_saude_ibs_cbs) || 60,
    certificadoValidade: r.certificado_validade || '2027-12-31'
  }),

  // Financial Management Mappers
  contaReceberToDb: (c: Partial<import('../types').ContaReceber>) => ({
    id: c.id,
    paciente_id: c.pacienteId || null,
    paciente_nome: c.pacienteNome,
    descricao: c.descricao,
    valor: c.valor || 0,
    valor_recebido: c.valorRecebido || 0,
    data_vencimento: c.dataVencimento,
    data_recebimento: c.dataRecebimento || null,
    status: c.status || 'Pendente',
    forma_pagamento: c.formaPagamento || 'PIX',
    categoria_id: c.categoriaId || null,
    categoria_nome: c.categoriaNome || null,
    observacoes: c.observacoes || null,
    nota_fiscal_id: c.notaFiscalId || null
  }),
  dbToContaReceber: (r: any): import('../types').ContaReceber => ({
    id: String(r.id),
    pacienteId: r.paciente_id || null,
    pacienteNome: r.paciente_nome || 'Cliente Diversos',
    descricao: r.descricao || '',
    valor: Number(r.valor) || 0,
    valorRecebido: Number(r.valor_recebido) || 0,
    dataVencimento: r.data_vencimento || '',
    dataRecebimento: r.data_recebimento || undefined,
    status: r.status || 'Pendente',
    formaPagamento: r.forma_pagamento || 'PIX',
    categoriaId: r.categoria_id || undefined,
    categoriaNome: r.categoria_nome || 'Geral',
    observacoes: r.observacoes || undefined,
    notaFiscalId: r.nota_fiscal_id || undefined,
    created_at: r.created_at || ''
  }),

  contaPagarToDb: (c: Partial<import('../types').ContaPagar>) => ({
    id: c.id,
    fornecedor_nome: c.fornecedorNome,
    prof_id: c.profId || null,
    descricao: c.descricao,
    valor: c.valor || 0,
    valor_pago: c.valorPago || 0,
    data_vencimento: c.dataVencimento,
    data_pagamento: c.dataPagamento || null,
    status: c.status || 'Pendente',
    forma_pagamento: c.formaPagamento || 'PIX',
    categoria_id: c.categoriaId || null,
    categoria_nome: c.categoriaNome || null,
    comprovante_url: c.comprovanteUrl || null,
    observacoes: c.observacoes || null
  }),
  dbToContaPagar: (r: any): import('../types').ContaPagar => ({
    id: String(r.id),
    fornecedorNome: r.fornecedor_nome || 'Fornecedor Diversos',
    profId: r.prof_id || null,
    descricao: r.descricao || '',
    valor: Number(r.valor) || 0,
    valorPago: Number(r.valor_pago) || 0,
    dataVencimento: r.data_vencimento || '',
    dataPagamento: r.data_pagamento || undefined,
    status: r.status || 'Pendente',
    formaPagamento: r.forma_pagamento || 'PIX',
    categoriaId: r.categoria_id || undefined,
    categoriaNome: r.categoria_nome || 'Geral',
    comprovanteUrl: r.comprovante_url || undefined,
    observacoes: r.observacoes || undefined,
    created_at: r.created_at || ''
  }),

  categoriaToDb: (cat: Partial<import('../types').CategoriaFinanceira>) => ({
    id: cat.id,
    nome: cat.nome,
    tipo: cat.tipo || 'Despesa',
    cor: cat.cor || '#6366f1',
    icone: cat.icone || 'Tag'
  }),
  dbToCategoria: (r: any): import('../types').CategoriaFinanceira => ({
    id: String(r.id),
    nome: r.nome || '',
    tipo: r.tipo || 'Despesa',
    cor: r.cor || '#6366f1',
    icone: r.icone || 'Tag'
  })
};

