-- =========================================================================
-- ClinicFlow — Script de Correção de Permissões e RLS (Fechamentos Mensais)
-- =========================================================================
-- Execute este script no Supabase SQL Editor para corrigir o erro 403 (Forbidden)
-- ao gravar fechamentos mensais e repasses de terapeutas.
-- =========================================================================

-- 1. Garantir que a tabela fechamentos_mensais existe e possui a restrição UNIQUE em competencia
CREATE TABLE IF NOT EXISTS fechamentos_mensais (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  competencia VARCHAR(7) NOT NULL UNIQUE,
  detalhes JSONB,
  confirmado_por VARCHAR(255),
  confirmado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Garantir índice / restrição UNIQUE em competencia se a tabela já existia sem a constraint
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fechamentos_mensais_competencia_key'
    ) THEN
        ALTER TABLE fechamentos_mensais ADD CONSTRAINT fechamentos_mensais_competencia_key UNIQUE (competencia);
    END IF;
EXCEPTION
    WHEN OTHERS THEN NULL;
END $$;

-- 2. Conceder permissões totais para as funções anon, authenticated e service_role
GRANT ALL ON TABLE fechamentos_mensais TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- 3. Configurar RLS (Row Level Security) permissivo para fechamentos_mensais
ALTER TABLE fechamentos_mensais ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permitir leitura publica fechamentos_mensais" ON fechamentos_mensais;
CREATE POLICY "Permitir leitura publica fechamentos_mensais" 
ON fechamentos_mensais FOR SELECT 
USING (true);

DROP POLICY IF EXISTS "Permitir insercao publica fechamentos_mensais" ON fechamentos_mensais;
CREATE POLICY "Permitir insercao publica fechamentos_mensais" 
ON fechamentos_mensais FOR INSERT 
WITH CHECK (true);

DROP POLICY IF EXISTS "Permitir atualizacao publica fechamentos_mensais" ON fechamentos_mensais;
CREATE POLICY "Permitir atualizacao publica fechamentos_mensais" 
ON fechamentos_mensais FOR UPDATE 
USING (true);

DROP POLICY IF EXISTS "Permitir exclusao publica fechamentos_mensais" ON fechamentos_mensais;
CREATE POLICY "Permitir exclusao publica fechamentos_mensais" 
ON fechamentos_mensais FOR DELETE 
USING (true);

-- 4. Repetir permissões e RLS para pagamentos_terapeutas
CREATE TABLE IF NOT EXISTS pagamentos_terapeutas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prof_id BIGINT,
  profissional VARCHAR(255),
  competencia VARCHAR(7),
  tipo VARCHAR(50),
  qtd_pacientes INT DEFAULT 0,
  valor NUMERIC(10,2) DEFAULT 0.00,
  status VARCHAR(50) DEFAULT 'pendente',
  valor_pago NUMERIC(10,2) DEFAULT 0.00,
  data_pagamento VARCHAR(20),
  nf_url TEXT,
  nf_nome VARCHAR(255),
  obs TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

GRANT ALL ON TABLE pagamentos_terapeutas TO anon, authenticated, service_role;

ALTER TABLE pagamentos_terapeutas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permitir leitura publica pagamentos_terapeutas" ON pagamentos_terapeutas;
CREATE POLICY "Permitir leitura publica pagamentos_terapeutas" 
ON pagamentos_terapeutas FOR SELECT 
USING (true);

DROP POLICY IF EXISTS "Permitir insercao publica pagamentos_terapeutas" ON pagamentos_terapeutas;
CREATE POLICY "Permitir insercao publica pagamentos_terapeutas" 
ON pagamentos_terapeutas FOR INSERT 
WITH CHECK (true);

DROP POLICY IF EXISTS "Permitir atualizacao publica pagamentos_terapeutas" ON pagamentos_terapeutas;
CREATE POLICY "Permitir atualizacao publica pagamentos_terapeutas" 
ON pagamentos_terapeutas FOR UPDATE 
USING (true);

DROP POLICY IF EXISTS "Permitir exclusao publica pagamentos_terapeutas" ON pagamentos_terapeutas;
CREATE POLICY "Permitir exclusao publica pagamentos_terapeutas" 
ON pagamentos_terapeutas FOR DELETE 
USING (true);
