-- SQL Script: Tabela de Prazos de Fechamento por Plano de Saúde no Supabase

CREATE TABLE IF NOT EXISTS public.fechamentos_planos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plano_id BIGINT REFERENCES public.planos_saude(id) ON DELETE SET NULL,
  plano_nome TEXT NOT NULL,
  plano_codigo TEXT NOT NULL DEFAULT '',
  data_entrega_inicial DATE NOT NULL,
  data_entrega_final DATE NOT NULL,
  data_pagamento DATE NOT NULL,
  observacoes TEXT,
  status TEXT NOT NULL DEFAULT 'ativo',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Índices para buscas performáticas
CREATE INDEX IF NOT EXISTS idx_fechamentos_planos_plano_nome ON public.fechamentos_planos(plano_nome);
CREATE INDEX IF NOT EXISTS idx_fechamentos_planos_datas ON public.fechamentos_planos(data_entrega_inicial, data_entrega_final);

-- Habilitar Row Level Security (RLS)
ALTER TABLE public.fechamentos_planos ENABLE ROW LEVEL SECURITY;

-- Política de RLS para permissão total de acesso
DROP POLICY IF EXISTS "Permitir acesso completo em fechamentos_planos" ON public.fechamentos_planos;
CREATE POLICY "Permitir acesso completo em fechamentos_planos"
  ON public.fechamentos_planos
  FOR ALL
  USING (true)
  WITH CHECK (true);
